research_candidates_task:
  description: >
    Conduct thorough research to find potential real candidates for the specified job.
    Utilize various online resources and databases to gather a comprehensive list of potential candidates.
    Ensure that the candidates meet the job requirements provided.

    Job Requirements:
    {job_requirements}
  expected_output: >
    A list of 2 potential candidates with their contact information and brief profiles highlighting their suitability.

validate_results_task:
  description: >
    Review the results provided by the other agents to ensure they contain only candidate profiles and not job offers.
    If any job offers are detected instead of candidate profiles, flag the results for correction and instruct the other agents to redo their tasks.
  expected_output: >
    A validation report indicating whether the results are correct. If incorrect, indicate the issues and request the tasks to be redone.

match_and_score_candidates_task:
  description: >
    Conduct thorough research to find candidates that match the following job requirements:
      - Requirements: {job_requirements}
      Use various databases and online resources to compile a list of potential candidates.
      The collected information must be in JSON format and should include only the following fields with one level of depth:
      - name
      - skills
      - position
      - email
      - linkedin
      Ensure that the candidates meet the specified requirements.
  expected_output: >
    A list of 2 potential candidates with the following fields:
      - name: "Candidate name",
      - skills: ["Skill 1", "Skill 2", "Skill 3"],
      - position: "Candidate Position",
      - email: "candidate email",
      - linkedin: "candidate linkedin"

outreach_strategy_task:
  description: >
    Develop a comprehensive strategy to reach out to the selected candidates.
    Create effective outreach methods and templates that can engage the candidates and encourage them to consider the job opportunity.

    Job Requirements:
    {job_requirements}
  expected_output: >
    A detailed list of outreach methods and templates ready for implementation, including communication strategies and engagement tactics in JSON format.

report_candidates_task:
  description: >
    Compile a comprehensive report for recruiters on the best candidates to put forward.
    Summarize the findings from the previous tasks and provide clear recommendations based on the job requirements.
  expected_output: >
    A detailed report formatted in JSON with the best candidates to pursue, no need to include the job requirements, including profiles, scores, and outreach strategies.