version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: python src/recruitment/main.py
    tty: true
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash", "/app/run.sh", "start"]
    command: ["start"]
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - NODE_ENV=development
      
volumes:
  db-data:
